# Generated by Django 4.1.2 on 2022-10-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default='', upload_to='musics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
